//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public string ID { get; set; }
        public System.DateTime dateOfDecision { get; set; }
        public string finalDecision { get; set; }
        public string Description { get; set; }
        public string madeBy_EO_ID { get; set; }
        public string relatedTo_requestNo { get; set; }
    
        public virtual EO EO { get; set; }
        public virtual PermitRequest PermitRequest { get; set; }
    }
}
