//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailArchive
    {
        public string emailID { get; set; }
        public System.DateTime emailDate { get; set; }
        public string reason { get; set; }
        public string sentTo_RE_ID { get; set; }
        public string sentBy_ID { get; set; }
        public string sentByType { get; set; }
    
        public virtual RE RE { get; set; }
    }
}
