//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group5_iPERMITDBEntities : DbContext
    {
        public Group5_iPERMITDBEntities()
            : base("name=Group5_iPERMITDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Decision> Decision { get; set; }
        public virtual DbSet<EmailArchive> EmailArchive { get; set; }
        public virtual DbSet<EnvironmentalPermits> EnvironmentalPermits { get; set; }
        public virtual DbSet<EO> EO { get; set; }
        public virtual DbSet<OPS_CPP> OPS_CPP { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Permit> Permit { get; set; }
        public virtual DbSet<PermitRequest> PermitRequest { get; set; }
        public virtual DbSet<RE> RE { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<RESite> RESite { get; set; }
    }
}
