//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string paymentMethod { get; set; }
        public bool isApproved { get; set; }
        public string PermitRequest_requestNo { get; set; }
        public string approvedBy_OPS_ID { get; set; }
    
        public virtual OPS_CPP OPS_CPP { get; set; }
        public virtual PermitRequest PermitRequest { get; set; }
    }
}
