//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermitRequest()
        {
            this.Decision = new HashSet<Decision>();
            this.Payment = new HashSet<Payment>();
            this.Permit = new HashSet<Permit>();
            this.RequestStatus = new HashSet<RequestStatus>();
        }
    
        public string requestNo { get; set; }
        public System.DateTime dateOfRequest { get; set; }
        public string activityDescription { get; set; }
        public System.DateTime activityStartDate { get; set; }
        public Nullable<System.DateTime> activityDuration { get; set; }
        public decimal permitFee { get; set; }
        public string requestedBy_RE_ID { get; set; }
        public string requestedPermit_permitID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decision> Decision { get; set; }
        public virtual EnvironmentalPermits EnvironmentalPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permit> Permit { get; set; }
        public virtual RE RE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestStatus> RequestStatus { get; set; }
    }
}
