//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatus
    {
        public int RequestStatusID { get; set; }
        public string permitRequestStatus { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public string PermitRequest_requestNo { get; set; }
        public string updatedBy_ID { get; set; }
        public string updatedByType { get; set; }
    
        public virtual PermitRequest PermitRequest { get; set; }
    }
}
