//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPERMIT_Group_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESite
    {
        public int RESiteID { get; set; }
        public string RE_ID { get; set; }
        public string siteAddress { get; set; }
        public string siteContactPerson { get; set; }
    
        public virtual RE RE { get; set; }
    }
}
